#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  aux_sym_transaction_token1 = 2,
  sym_account = 3,
  anon_sym_POUND = 4,
  anon_sym_SEMI = 5,
  aux_sym_comment_token1 = 6,
  anon_sym_STAR = 7,
  anon_sym_DOT = 8,
  anon_sym_SPACE = 9,
  aux_sym__quantity_number_token1 = 10,
  aux_sym__quantity_number_token2 = 11,
  anon_sym_s = 12,
  anon_sym_m = 13,
  anon_sym_h = 14,
  anon_sym_d = 15,
  anon_sym_w = 16,
  anon_sym_mo = 17,
  anon_sym_y = 18,
  anon_sym_TAB = 19,
  sym__dsep = 20,
  sym__2d = 21,
  sym__4d = 22,
  sym_source_file = 23,
  sym_day_entry = 24,
  sym_transaction = 25,
  sym_comment = 26,
  sym_quantity = 27,
  sym_date = 28,
  sym_org_heading = 29,
  aux_sym__quantity_dot = 30,
  sym__quantity_number = 31,
  sym__unit = 32,
  aux_sym__whitespace = 33,
  sym__single_date = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_day_entry_repeat1 = 36,
  aux_sym_org_heading_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [aux_sym_transaction_token1] = "transaction_token1",
  [sym_account] = "account",
  [anon_sym_POUND] = "#",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR] = "*",
  [anon_sym_DOT] = ".",
  [anon_sym_SPACE] = " ",
  [aux_sym__quantity_number_token1] = "_quantity_number_token1",
  [aux_sym__quantity_number_token2] = "_quantity_number_token2",
  [anon_sym_s] = "s",
  [anon_sym_m] = "m",
  [anon_sym_h] = "h",
  [anon_sym_d] = "d",
  [anon_sym_w] = "w",
  [anon_sym_mo] = "mo",
  [anon_sym_y] = "y",
  [anon_sym_TAB] = "\t",
  [sym__dsep] = "_dsep",
  [sym__2d] = "_2d",
  [sym__4d] = "_4d",
  [sym_source_file] = "source_file",
  [sym_day_entry] = "day_entry",
  [sym_transaction] = "transaction",
  [sym_comment] = "comment",
  [sym_quantity] = "quantity",
  [sym_date] = "date",
  [sym_org_heading] = "org_heading",
  [aux_sym__quantity_dot] = "_quantity_dot",
  [sym__quantity_number] = "_quantity_number",
  [sym__unit] = "_unit",
  [aux_sym__whitespace] = "_whitespace",
  [sym__single_date] = "_single_date",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_day_entry_repeat1] = "day_entry_repeat1",
  [aux_sym_org_heading_repeat1] = "org_heading_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_transaction_token1] = aux_sym_transaction_token1,
  [sym_account] = sym_account,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym__quantity_number_token1] = aux_sym__quantity_number_token1,
  [aux_sym__quantity_number_token2] = aux_sym__quantity_number_token2,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_m] = anon_sym_m,
  [anon_sym_h] = anon_sym_h,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_w] = anon_sym_w,
  [anon_sym_mo] = anon_sym_mo,
  [anon_sym_y] = anon_sym_y,
  [anon_sym_TAB] = anon_sym_TAB,
  [sym__dsep] = sym__dsep,
  [sym__2d] = sym__2d,
  [sym__4d] = sym__4d,
  [sym_source_file] = sym_source_file,
  [sym_day_entry] = sym_day_entry,
  [sym_transaction] = sym_transaction,
  [sym_comment] = sym_comment,
  [sym_quantity] = sym_quantity,
  [sym_date] = sym_date,
  [sym_org_heading] = sym_org_heading,
  [aux_sym__quantity_dot] = aux_sym__quantity_dot,
  [sym__quantity_number] = sym__quantity_number,
  [sym__unit] = sym__unit,
  [aux_sym__whitespace] = aux_sym__whitespace,
  [sym__single_date] = sym__single_date,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_day_entry_repeat1] = aux_sym_day_entry_repeat1,
  [aux_sym_org_heading_repeat1] = aux_sym_org_heading_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_transaction_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_account] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quantity_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__quantity_number_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_m] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_h] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_y] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [sym__dsep] = {
    .visible = false,
    .named = true,
  },
  [sym__2d] = {
    .visible = false,
    .named = true,
  },
  [sym__4d] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_day_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_transaction] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_org_heading] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__quantity_dot] = {
    .visible = false,
    .named = false,
  },
  [sym__quantity_number] = {
    .visible = false,
    .named = true,
  },
  [sym__unit] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__whitespace] = {
    .visible = false,
    .named = false,
  },
  [sym__single_date] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_day_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_org_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 23,
  [41] = 39,
  [42] = 42,
  [43] = 43,
  [44] = 43,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(37);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == 'd') ADVANCE(32);
      if (lookahead == 'h') ADVANCE(31);
      if (lookahead == 'm') ADVANCE(30);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == 'w') ADVANCE(33);
      if (lookahead == 'y') ADVANCE(35);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(39);
      if ((11 <= lookahead && lookahead <= '\r')) ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(37);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ';') ADVANCE(20);
      if ((11 <= lookahead && lookahead <= '\r')) ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ';') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '#' &&
          (lookahead < '0' || '9' < lookahead) &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(13);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(39);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '*' &&
          (lookahead < '0' || '9' < lookahead) &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(18);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == 'd') ADVANCE(32);
      if (lookahead == 'h') ADVANCE(31);
      if (lookahead == 'm') ADVANCE(30);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == 'w') ADVANCE(33);
      if (lookahead == 'y') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(38);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == ';') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_transaction_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_account);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__quantity_number_token1);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__quantity_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__quantity_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_m);
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_h);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_mo);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_y);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(17);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__dsep);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__2d);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__2d);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__4d);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 10},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 21},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 10},
  [58] = {.lex_state = 10},
  [59] = {.lex_state = 10},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 10},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 10},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 10},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 10},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_transaction_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [aux_sym__quantity_number_token1] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_m] = ACTIONS(1),
    [anon_sym_h] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [anon_sym_mo] = ACTIONS(1),
    [anon_sym_y] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [sym__dsep] = ACTIONS(1),
    [sym__2d] = ACTIONS(1),
    [sym__4d] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(66),
    [sym_day_entry] = STATE(10),
    [sym_comment] = STATE(67),
    [sym_date] = STATE(69),
    [sym_org_heading] = STATE(46),
    [sym__single_date] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_org_heading_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [sym__2d] = ACTIONS(11),
    [sym__4d] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      sym_account,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(24), 1,
      anon_sym_SPACE,
    ACTIONS(26), 1,
      anon_sym_TAB,
    STATE(30), 1,
      aux_sym__whitespace,
    STATE(39), 1,
      aux_sym_org_heading_repeat1,
    STATE(56), 1,
      sym_org_heading,
    ACTIONS(17), 2,
      anon_sym_LF,
      sym__2d,
    STATE(6), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [36] = 10,
    ACTIONS(19), 1,
      sym_account,
    ACTIONS(24), 1,
      anon_sym_SPACE,
    ACTIONS(26), 1,
      anon_sym_TAB,
    ACTIONS(32), 1,
      anon_sym_STAR,
    STATE(30), 1,
      aux_sym__whitespace,
    STATE(39), 1,
      aux_sym_org_heading_repeat1,
    STATE(56), 1,
      sym_org_heading,
    ACTIONS(30), 2,
      anon_sym_LF,
      sym__2d,
    STATE(4), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [72] = 10,
    ACTIONS(39), 1,
      sym_account,
    ACTIONS(42), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_SPACE,
    ACTIONS(48), 1,
      anon_sym_TAB,
    STATE(30), 1,
      aux_sym__whitespace,
    STATE(39), 1,
      aux_sym_org_heading_repeat1,
    STATE(56), 1,
      sym_org_heading,
    ACTIONS(37), 2,
      anon_sym_LF,
      sym__2d,
    STATE(4), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [108] = 10,
    ACTIONS(19), 1,
      sym_account,
    ACTIONS(24), 1,
      anon_sym_SPACE,
    ACTIONS(26), 1,
      anon_sym_TAB,
    ACTIONS(55), 1,
      anon_sym_STAR,
    STATE(30), 1,
      aux_sym__whitespace,
    STATE(39), 1,
      aux_sym_org_heading_repeat1,
    STATE(56), 1,
      sym_org_heading,
    ACTIONS(53), 2,
      anon_sym_LF,
      sym__2d,
    STATE(3), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [144] = 10,
    ACTIONS(19), 1,
      sym_account,
    ACTIONS(24), 1,
      anon_sym_SPACE,
    ACTIONS(26), 1,
      anon_sym_TAB,
    ACTIONS(55), 1,
      anon_sym_STAR,
    STATE(30), 1,
      aux_sym__whitespace,
    STATE(39), 1,
      aux_sym_org_heading_repeat1,
    STATE(56), 1,
      sym_org_heading,
    ACTIONS(53), 2,
      anon_sym_LF,
      sym__2d,
    STATE(4), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [180] = 13,
    ACTIONS(58), 1,
      anon_sym_LF,
    ACTIONS(60), 1,
      aux_sym_transaction_token1,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(64), 1,
      anon_sym_SPACE,
    ACTIONS(66), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(68), 1,
      aux_sym__quantity_number_token2,
    ACTIONS(70), 1,
      anon_sym_TAB,
    STATE(24), 1,
      aux_sym__whitespace,
    STATE(31), 1,
      sym_quantity,
    STATE(36), 1,
      aux_sym__quantity_dot,
    STATE(42), 1,
      sym__quantity_number,
    STATE(48), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
  [221] = 13,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(64), 1,
      anon_sym_SPACE,
    ACTIONS(66), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(68), 1,
      aux_sym__quantity_number_token2,
    ACTIONS(72), 1,
      anon_sym_LF,
    ACTIONS(74), 1,
      aux_sym_transaction_token1,
    ACTIONS(76), 1,
      anon_sym_TAB,
    STATE(25), 1,
      aux_sym__whitespace,
    STATE(33), 1,
      sym_quantity,
    STATE(36), 1,
      aux_sym__quantity_dot,
    STATE(42), 1,
      sym__quantity_number,
    STATE(59), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
  [262] = 12,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_LF,
    ACTIONS(86), 1,
      anon_sym_STAR,
    ACTIONS(89), 1,
      sym__2d,
    ACTIONS(92), 1,
      sym__4d,
    STATE(41), 1,
      aux_sym_org_heading_repeat1,
    STATE(46), 1,
      sym_org_heading,
    STATE(60), 1,
      sym__single_date,
    STATE(67), 1,
      sym_comment,
    STATE(69), 1,
      sym_date,
    ACTIONS(83), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    STATE(9), 2,
      sym_day_entry,
      aux_sym_source_file_repeat1,
  [301] = 12,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(11), 1,
      sym__2d,
    ACTIONS(13), 1,
      sym__4d,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      anon_sym_LF,
    STATE(41), 1,
      aux_sym_org_heading_repeat1,
    STATE(46), 1,
      sym_org_heading,
    STATE(60), 1,
      sym__single_date,
    STATE(67), 1,
      sym_comment,
    STATE(69), 1,
      sym_date,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    STATE(9), 2,
      sym_day_entry,
      aux_sym_source_file_repeat1,
  [340] = 13,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(64), 1,
      anon_sym_SPACE,
    ACTIONS(66), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(68), 1,
      aux_sym__quantity_number_token2,
    ACTIONS(99), 1,
      anon_sym_LF,
    ACTIONS(101), 1,
      aux_sym_transaction_token1,
    ACTIONS(103), 1,
      anon_sym_TAB,
    STATE(34), 1,
      aux_sym__whitespace,
    STATE(35), 1,
      sym_quantity,
    STATE(36), 1,
      aux_sym__quantity_dot,
    STATE(42), 1,
      sym__quantity_number,
    STATE(54), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
  [381] = 12,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(68), 1,
      aux_sym__quantity_number_token2,
    ACTIONS(105), 1,
      anon_sym_LF,
    ACTIONS(107), 1,
      anon_sym_SPACE,
    ACTIONS(109), 1,
      anon_sym_TAB,
    STATE(24), 1,
      aux_sym__whitespace,
    STATE(31), 1,
      sym_quantity,
    STATE(36), 1,
      aux_sym__quantity_dot,
    STATE(42), 1,
      sym__quantity_number,
    STATE(48), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
  [419] = 12,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(68), 1,
      aux_sym__quantity_number_token2,
    ACTIONS(107), 1,
      anon_sym_SPACE,
    ACTIONS(111), 1,
      anon_sym_LF,
    ACTIONS(113), 1,
      anon_sym_TAB,
    STATE(27), 1,
      sym_quantity,
    STATE(28), 1,
      aux_sym__whitespace,
    STATE(36), 1,
      aux_sym__quantity_dot,
    STATE(42), 1,
      sym__quantity_number,
    STATE(58), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
  [457] = 4,
    ACTIONS(119), 1,
      anon_sym_m,
    STATE(38), 1,
      sym__unit,
    ACTIONS(115), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
    ACTIONS(117), 6,
      anon_sym_s,
      anon_sym_h,
      anon_sym_d,
      anon_sym_w,
      anon_sym_mo,
      anon_sym_y,
  [479] = 12,
    ACTIONS(62), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(68), 1,
      aux_sym__quantity_number_token2,
    ACTIONS(107), 1,
      anon_sym_SPACE,
    ACTIONS(121), 1,
      anon_sym_LF,
    ACTIONS(123), 1,
      anon_sym_TAB,
    STATE(25), 1,
      aux_sym__whitespace,
    STATE(33), 1,
      sym_quantity,
    STATE(36), 1,
      aux_sym__quantity_dot,
    STATE(42), 1,
      sym__quantity_number,
    STATE(59), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
  [517] = 2,
    ACTIONS(127), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [532] = 2,
    ACTIONS(131), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [547] = 2,
    ACTIONS(135), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [562] = 2,
    ACTIONS(139), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [577] = 2,
    ACTIONS(143), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(141), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [592] = 2,
    ACTIONS(147), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(145), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [607] = 2,
    ACTIONS(151), 4,
      anon_sym_LF,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(149), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [622] = 4,
    ACTIONS(158), 1,
      sym__2d,
    STATE(23), 1,
      aux_sym__whitespace,
    ACTIONS(155), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
    ACTIONS(153), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [639] = 5,
    ACTIONS(111), 1,
      anon_sym_LF,
    STATE(23), 1,
      aux_sym__whitespace,
    STATE(58), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(160), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [657] = 5,
    ACTIONS(105), 1,
      anon_sym_LF,
    STATE(23), 1,
      aux_sym__whitespace,
    STATE(48), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(160), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [675] = 5,
    ACTIONS(162), 1,
      anon_sym_LF,
    STATE(23), 1,
      aux_sym__whitespace,
    STATE(65), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(160), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [693] = 5,
    ACTIONS(164), 1,
      anon_sym_LF,
    STATE(26), 1,
      aux_sym__whitespace,
    STATE(62), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(166), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [711] = 5,
    ACTIONS(164), 1,
      anon_sym_LF,
    STATE(23), 1,
      aux_sym__whitespace,
    STATE(62), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(160), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [729] = 2,
    ACTIONS(168), 1,
      sym__2d,
    ACTIONS(78), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      sym__4d,
  [741] = 7,
    ACTIONS(170), 1,
      sym_account,
    ACTIONS(172), 1,
      anon_sym_STAR,
    ACTIONS(174), 1,
      anon_sym_SPACE,
    ACTIONS(176), 1,
      anon_sym_TAB,
    STATE(39), 1,
      aux_sym_org_heading_repeat1,
    STATE(40), 1,
      aux_sym__whitespace,
    STATE(68), 1,
      sym_org_heading,
  [763] = 5,
    ACTIONS(111), 1,
      anon_sym_LF,
    STATE(28), 1,
      aux_sym__whitespace,
    STATE(58), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(113), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [781] = 3,
    STATE(32), 1,
      aux_sym__quantity_dot,
    ACTIONS(180), 2,
      anon_sym_DOT,
      anon_sym_SPACE,
    ACTIONS(178), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_TAB,
  [795] = 5,
    ACTIONS(105), 1,
      anon_sym_LF,
    STATE(24), 1,
      aux_sym__whitespace,
    STATE(48), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(109), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [813] = 5,
    ACTIONS(121), 1,
      anon_sym_LF,
    STATE(23), 1,
      aux_sym__whitespace,
    STATE(59), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(160), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [831] = 5,
    ACTIONS(121), 1,
      anon_sym_LF,
    STATE(25), 1,
      aux_sym__whitespace,
    STATE(59), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(123), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [849] = 4,
    ACTIONS(185), 1,
      anon_sym_DOT,
    ACTIONS(187), 1,
      anon_sym_SPACE,
    STATE(32), 1,
      aux_sym__quantity_dot,
    ACTIONS(183), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_TAB,
  [865] = 2,
    ACTIONS(193), 1,
      anon_sym_DOT,
    ACTIONS(190), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
  [876] = 1,
    ACTIONS(195), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
  [884] = 4,
    ACTIONS(197), 1,
      anon_sym_STAR,
    STATE(44), 1,
      aux_sym__whitespace,
    STATE(45), 1,
      aux_sym_org_heading_repeat1,
    ACTIONS(199), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [898] = 5,
    ACTIONS(153), 1,
      anon_sym_STAR,
    ACTIONS(158), 1,
      sym_account,
    ACTIONS(201), 1,
      anon_sym_SPACE,
    ACTIONS(204), 1,
      anon_sym_TAB,
    STATE(40), 1,
      aux_sym__whitespace,
  [914] = 4,
    ACTIONS(197), 1,
      anon_sym_STAR,
    STATE(43), 1,
      aux_sym__whitespace,
    STATE(45), 1,
      aux_sym_org_heading_repeat1,
    ACTIONS(207), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [928] = 1,
    ACTIONS(183), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
  [936] = 4,
    ACTIONS(209), 1,
      sym__2d,
    ACTIONS(211), 1,
      sym__4d,
    STATE(23), 1,
      aux_sym__whitespace,
    ACTIONS(160), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [950] = 4,
    ACTIONS(174), 1,
      anon_sym_SPACE,
    ACTIONS(176), 1,
      anon_sym_TAB,
    ACTIONS(209), 1,
      sym_account,
    STATE(40), 1,
      aux_sym__whitespace,
  [963] = 3,
    ACTIONS(213), 1,
      anon_sym_STAR,
    STATE(45), 1,
      aux_sym_org_heading_repeat1,
    ACTIONS(216), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [974] = 4,
    ACTIONS(11), 1,
      sym__2d,
    ACTIONS(13), 1,
      sym__4d,
    STATE(53), 1,
      sym_date,
    STATE(60), 1,
      sym__single_date,
  [987] = 2,
    ACTIONS(218), 1,
      anon_sym_LF,
    ACTIONS(220), 1,
      sym__dsep,
  [994] = 1,
    ACTIONS(111), 1,
      anon_sym_LF,
  [998] = 1,
    ACTIONS(220), 1,
      sym__dsep,
  [1002] = 1,
    ACTIONS(222), 1,
      sym__2d,
  [1006] = 1,
    ACTIONS(224), 1,
      sym__dsep,
  [1010] = 1,
    ACTIONS(226), 1,
      sym__dsep,
  [1014] = 1,
    ACTIONS(228), 1,
      anon_sym_LF,
  [1018] = 1,
    ACTIONS(121), 1,
      anon_sym_LF,
  [1022] = 1,
    ACTIONS(230), 1,
      aux_sym_comment_token1,
  [1026] = 1,
    ACTIONS(232), 1,
      sym_account,
  [1030] = 1,
    ACTIONS(234), 1,
      sym__2d,
  [1034] = 1,
    ACTIONS(164), 1,
      anon_sym_LF,
  [1038] = 1,
    ACTIONS(105), 1,
      anon_sym_LF,
  [1042] = 1,
    ACTIONS(236), 1,
      anon_sym_LF,
  [1046] = 1,
    ACTIONS(238), 1,
      sym__2d,
  [1050] = 1,
    ACTIONS(162), 1,
      anon_sym_LF,
  [1054] = 1,
    ACTIONS(240), 1,
      anon_sym_LF,
  [1058] = 1,
    ACTIONS(242), 1,
      anon_sym_LF,
  [1062] = 1,
    ACTIONS(244), 1,
      anon_sym_LF,
  [1066] = 1,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
  [1070] = 1,
    ACTIONS(248), 1,
      anon_sym_LF,
  [1074] = 1,
    ACTIONS(250), 1,
      sym_account,
  [1078] = 1,
    ACTIONS(252), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 221,
  [SMALL_STATE(9)] = 262,
  [SMALL_STATE(10)] = 301,
  [SMALL_STATE(11)] = 340,
  [SMALL_STATE(12)] = 381,
  [SMALL_STATE(13)] = 419,
  [SMALL_STATE(14)] = 457,
  [SMALL_STATE(15)] = 479,
  [SMALL_STATE(16)] = 517,
  [SMALL_STATE(17)] = 532,
  [SMALL_STATE(18)] = 547,
  [SMALL_STATE(19)] = 562,
  [SMALL_STATE(20)] = 577,
  [SMALL_STATE(21)] = 592,
  [SMALL_STATE(22)] = 607,
  [SMALL_STATE(23)] = 622,
  [SMALL_STATE(24)] = 639,
  [SMALL_STATE(25)] = 657,
  [SMALL_STATE(26)] = 675,
  [SMALL_STATE(27)] = 693,
  [SMALL_STATE(28)] = 711,
  [SMALL_STATE(29)] = 729,
  [SMALL_STATE(30)] = 741,
  [SMALL_STATE(31)] = 763,
  [SMALL_STATE(32)] = 781,
  [SMALL_STATE(33)] = 795,
  [SMALL_STATE(34)] = 813,
  [SMALL_STATE(35)] = 831,
  [SMALL_STATE(36)] = 849,
  [SMALL_STATE(37)] = 865,
  [SMALL_STATE(38)] = 876,
  [SMALL_STATE(39)] = 884,
  [SMALL_STATE(40)] = 898,
  [SMALL_STATE(41)] = 914,
  [SMALL_STATE(42)] = 928,
  [SMALL_STATE(43)] = 936,
  [SMALL_STATE(44)] = 950,
  [SMALL_STATE(45)] = 963,
  [SMALL_STATE(46)] = 974,
  [SMALL_STATE(47)] = 987,
  [SMALL_STATE(48)] = 994,
  [SMALL_STATE(49)] = 998,
  [SMALL_STATE(50)] = 1002,
  [SMALL_STATE(51)] = 1006,
  [SMALL_STATE(52)] = 1010,
  [SMALL_STATE(53)] = 1014,
  [SMALL_STATE(54)] = 1018,
  [SMALL_STATE(55)] = 1022,
  [SMALL_STATE(56)] = 1026,
  [SMALL_STATE(57)] = 1030,
  [SMALL_STATE(58)] = 1034,
  [SMALL_STATE(59)] = 1038,
  [SMALL_STATE(60)] = 1042,
  [SMALL_STATE(61)] = 1046,
  [SMALL_STATE(62)] = 1050,
  [SMALL_STATE(63)] = 1054,
  [SMALL_STATE(64)] = 1058,
  [SMALL_STATE(65)] = 1062,
  [SMALL_STATE(66)] = 1066,
  [SMALL_STATE(67)] = 1070,
  [SMALL_STATE(68)] = 1074,
  [SMALL_STATE(69)] = 1078,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_entry, 2),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day_entry, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_day_entry, 2), SHIFT(39),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_entry, 4),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day_entry, 4),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_day_entry, 4), SHIFT(39),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_day_entry_repeat1, 2),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_day_entry_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(11),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(39),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(30),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(30),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_entry, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day_entry, 3),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_day_entry, 3), SHIFT(39),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(41),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quantity_number, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 8),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 8),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 7),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 7),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 6),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 6),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 5),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 5),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__whitespace, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__whitespace, 2), SHIFT_REPEAT(23),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__whitespace, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__quantity_dot, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quantity_dot, 2), SHIFT_REPEAT(32),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quantity, 1), SHIFT(32),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quantity_dot, 1), REDUCE(aux_sym__whitespace, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__quantity_dot, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quantity_number, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__whitespace, 2), SHIFT_REPEAT(40),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__whitespace, 2), SHIFT_REPEAT(40),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_org_heading, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_org_heading, 2),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_org_heading_repeat1, 2), SHIFT_REPEAT(45),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_org_heading_repeat1, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_date, 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_date, 5),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [246] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_timedot(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
