#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  aux_sym_transaction_token1 = 2,
  sym_account = 3,
  anon_sym_POUND = 4,
  anon_sym_SEMI = 5,
  aux_sym_comment_token1 = 6,
  anon_sym_STAR = 7,
  anon_sym_DOT = 8,
  anon_sym_SPACE = 9,
  aux_sym__quantity_number_token1 = 10,
  aux_sym__quantity_number_token2 = 11,
  anon_sym_s = 12,
  anon_sym_m = 13,
  anon_sym_h = 14,
  anon_sym_d = 15,
  anon_sym_w = 16,
  anon_sym_mo = 17,
  anon_sym_y = 18,
  anon_sym_TAB = 19,
  sym__dsep = 20,
  sym__2d = 21,
  sym__4d = 22,
  sym_source_file = 23,
  sym_day_entry = 24,
  sym_transaction = 25,
  sym_comment = 26,
  sym_quantity = 27,
  sym_date = 28,
  sym_org_heading = 29,
  aux_sym__quantity_dot = 30,
  sym__quantity_number = 31,
  sym__unit = 32,
  aux_sym__whitespace = 33,
  sym__single_date = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_day_entry_repeat1 = 36,
  aux_sym_org_heading_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [aux_sym_transaction_token1] = "transaction_token1",
  [sym_account] = "account",
  [anon_sym_POUND] = "#",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR] = "*",
  [anon_sym_DOT] = ".",
  [anon_sym_SPACE] = " ",
  [aux_sym__quantity_number_token1] = "_quantity_number_token1",
  [aux_sym__quantity_number_token2] = "_quantity_number_token2",
  [anon_sym_s] = "s",
  [anon_sym_m] = "m",
  [anon_sym_h] = "h",
  [anon_sym_d] = "d",
  [anon_sym_w] = "w",
  [anon_sym_mo] = "mo",
  [anon_sym_y] = "y",
  [anon_sym_TAB] = "\t",
  [sym__dsep] = "_dsep",
  [sym__2d] = "_2d",
  [sym__4d] = "_4d",
  [sym_source_file] = "source_file",
  [sym_day_entry] = "day_entry",
  [sym_transaction] = "transaction",
  [sym_comment] = "comment",
  [sym_quantity] = "quantity",
  [sym_date] = "date",
  [sym_org_heading] = "org_heading",
  [aux_sym__quantity_dot] = "_quantity_dot",
  [sym__quantity_number] = "_quantity_number",
  [sym__unit] = "_unit",
  [aux_sym__whitespace] = "_whitespace",
  [sym__single_date] = "_single_date",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_day_entry_repeat1] = "day_entry_repeat1",
  [aux_sym_org_heading_repeat1] = "org_heading_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_transaction_token1] = aux_sym_transaction_token1,
  [sym_account] = sym_account,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym__quantity_number_token1] = aux_sym__quantity_number_token1,
  [aux_sym__quantity_number_token2] = aux_sym__quantity_number_token2,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_m] = anon_sym_m,
  [anon_sym_h] = anon_sym_h,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_w] = anon_sym_w,
  [anon_sym_mo] = anon_sym_mo,
  [anon_sym_y] = anon_sym_y,
  [anon_sym_TAB] = anon_sym_TAB,
  [sym__dsep] = sym__dsep,
  [sym__2d] = sym__2d,
  [sym__4d] = sym__4d,
  [sym_source_file] = sym_source_file,
  [sym_day_entry] = sym_day_entry,
  [sym_transaction] = sym_transaction,
  [sym_comment] = sym_comment,
  [sym_quantity] = sym_quantity,
  [sym_date] = sym_date,
  [sym_org_heading] = sym_org_heading,
  [aux_sym__quantity_dot] = aux_sym__quantity_dot,
  [sym__quantity_number] = sym__quantity_number,
  [sym__unit] = sym__unit,
  [aux_sym__whitespace] = aux_sym__whitespace,
  [sym__single_date] = sym__single_date,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_day_entry_repeat1] = aux_sym_day_entry_repeat1,
  [aux_sym_org_heading_repeat1] = aux_sym_org_heading_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_transaction_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_account] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quantity_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__quantity_number_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_m] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_h] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_y] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [sym__dsep] = {
    .visible = false,
    .named = true,
  },
  [sym__2d] = {
    .visible = false,
    .named = true,
  },
  [sym__4d] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_day_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_transaction] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_quantity] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_org_heading] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__quantity_dot] = {
    .visible = false,
    .named = false,
  },
  [sym__quantity_number] = {
    .visible = false,
    .named = true,
  },
  [sym__unit] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__whitespace] = {
    .visible = false,
    .named = false,
  },
  [sym__single_date] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_day_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_org_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 17,
  [37] = 34,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(33);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == 'h') ADVANCE(28);
      if (lookahead == 'm') ADVANCE(27);
      if (lookahead == 's') ADVANCE(26);
      if (lookahead == 'w') ADVANCE(30);
      if (lookahead == 'y') ADVANCE(32);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(33);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ';') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(12);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(13);
      if (('-' <= lookahead && lookahead <= '/')) ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '*' &&
          (lookahead < '0' || '9' < lookahead) &&
          lookahead != ';') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(16);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(34);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == ';') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_transaction_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_account);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_account);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__quantity_number_token1);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__quantity_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__quantity_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_m);
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_h);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_mo);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_y);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_TAB);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(15);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__dsep);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__2d);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__2d);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__4d);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 19},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 10},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [aux_sym__quantity_number_token1] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_m] = ACTIONS(1),
    [anon_sym_h] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [anon_sym_mo] = ACTIONS(1),
    [anon_sym_y] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [sym__dsep] = ACTIONS(1),
    [sym__2d] = ACTIONS(1),
    [sym__4d] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(55),
    [sym_day_entry] = STATE(8),
    [sym_comment] = STATE(51),
    [sym_date] = STATE(48),
    [sym_org_heading] = STATE(39),
    [sym__single_date] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_org_heading_repeat1] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [sym__2d] = ACTIONS(11),
    [sym__4d] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      sym_account,
    ACTIONS(19), 1,
      anon_sym_STAR,
    ACTIONS(22), 1,
      anon_sym_SPACE,
    ACTIONS(24), 1,
      anon_sym_TAB,
    ACTIONS(26), 1,
      sym__2d,
    STATE(29), 1,
      aux_sym__whitespace,
    STATE(32), 1,
      aux_sym_org_heading_repeat1,
    STATE(61), 1,
      sym_org_heading,
    STATE(3), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(15), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [36] = 10,
    ACTIONS(30), 1,
      sym_account,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(36), 1,
      anon_sym_SPACE,
    ACTIONS(39), 1,
      anon_sym_TAB,
    ACTIONS(42), 1,
      sym__2d,
    STATE(29), 1,
      aux_sym__whitespace,
    STATE(32), 1,
      aux_sym_org_heading_repeat1,
    STATE(61), 1,
      sym_org_heading,
    STATE(3), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(28), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [72] = 10,
    ACTIONS(17), 1,
      sym_account,
    ACTIONS(22), 1,
      anon_sym_SPACE,
    ACTIONS(24), 1,
      anon_sym_TAB,
    ACTIONS(46), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      sym__2d,
    STATE(29), 1,
      aux_sym__whitespace,
    STATE(32), 1,
      aux_sym_org_heading_repeat1,
    STATE(61), 1,
      sym_org_heading,
    STATE(2), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [108] = 10,
    ACTIONS(17), 1,
      sym_account,
    ACTIONS(22), 1,
      anon_sym_SPACE,
    ACTIONS(24), 1,
      anon_sym_TAB,
    ACTIONS(53), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      sym__2d,
    STATE(29), 1,
      aux_sym__whitespace,
    STATE(32), 1,
      aux_sym_org_heading_repeat1,
    STATE(61), 1,
      sym_org_heading,
    STATE(6), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(51), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [144] = 10,
    ACTIONS(17), 1,
      sym_account,
    ACTIONS(22), 1,
      anon_sym_SPACE,
    ACTIONS(24), 1,
      anon_sym_TAB,
    ACTIONS(46), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      sym__2d,
    STATE(29), 1,
      aux_sym__whitespace,
    STATE(32), 1,
      aux_sym_org_heading_repeat1,
    STATE(61), 1,
      sym_org_heading,
    STATE(3), 2,
      sym_transaction,
      aux_sym_day_entry_repeat1,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [180] = 12,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_LF,
    ACTIONS(66), 1,
      anon_sym_STAR,
    ACTIONS(69), 1,
      sym__2d,
    ACTIONS(72), 1,
      sym__4d,
    STATE(31), 1,
      aux_sym_org_heading_repeat1,
    STATE(39), 1,
      sym_org_heading,
    STATE(44), 1,
      sym__single_date,
    STATE(48), 1,
      sym_date,
    STATE(51), 1,
      sym_comment,
    ACTIONS(63), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    STATE(7), 2,
      sym_day_entry,
      aux_sym_source_file_repeat1,
  [219] = 12,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(11), 1,
      sym__2d,
    ACTIONS(13), 1,
      sym__4d,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_LF,
    STATE(31), 1,
      aux_sym_org_heading_repeat1,
    STATE(39), 1,
      sym_org_heading,
    STATE(44), 1,
      sym__single_date,
    STATE(48), 1,
      sym_date,
    STATE(51), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    STATE(7), 2,
      sym_day_entry,
      aux_sym_source_file_repeat1,
  [258] = 4,
    ACTIONS(83), 1,
      anon_sym_m,
    STATE(33), 1,
      sym__unit,
    ACTIONS(79), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
    ACTIONS(81), 6,
      anon_sym_s,
      anon_sym_h,
      anon_sym_d,
      anon_sym_w,
      anon_sym_mo,
      anon_sym_y,
  [280] = 2,
    ACTIONS(87), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [295] = 2,
    ACTIONS(91), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(89), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [310] = 2,
    ACTIONS(95), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [325] = 2,
    ACTIONS(99), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(97), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [340] = 2,
    ACTIONS(103), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(101), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [355] = 2,
    ACTIONS(107), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(105), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [370] = 2,
    ACTIONS(111), 3,
      sym_account,
      anon_sym_TAB,
      sym__2d,
    ACTIONS(109), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_SPACE,
      sym__4d,
  [385] = 4,
    ACTIONS(118), 1,
      sym__2d,
    STATE(17), 1,
      aux_sym__whitespace,
    ACTIONS(115), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
    ACTIONS(113), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      sym__4d,
  [402] = 3,
    STATE(18), 1,
      aux_sym__quantity_dot,
    ACTIONS(122), 2,
      anon_sym_DOT,
      anon_sym_SPACE,
    ACTIONS(120), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_TAB,
  [416] = 6,
    ACTIONS(127), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(129), 1,
      aux_sym__quantity_number_token2,
    STATE(22), 1,
      aux_sym__quantity_dot,
    STATE(23), 1,
      sym_quantity,
    STATE(35), 1,
      sym__quantity_number,
    ACTIONS(125), 2,
      anon_sym_DOT,
      anon_sym_SPACE,
  [436] = 6,
    ACTIONS(127), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(129), 1,
      aux_sym__quantity_number_token2,
    STATE(22), 1,
      aux_sym__quantity_dot,
    STATE(25), 1,
      sym_quantity,
    STATE(35), 1,
      sym__quantity_number,
    ACTIONS(125), 2,
      anon_sym_DOT,
      anon_sym_SPACE,
  [456] = 2,
    ACTIONS(131), 1,
      sym__2d,
    ACTIONS(58), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_STAR,
      sym__4d,
  [468] = 4,
    ACTIONS(135), 1,
      anon_sym_DOT,
    ACTIONS(137), 1,
      anon_sym_SPACE,
    STATE(18), 1,
      aux_sym__quantity_dot,
    ACTIONS(133), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_TAB,
  [484] = 5,
    ACTIONS(140), 1,
      anon_sym_LF,
    STATE(24), 1,
      aux_sym__whitespace,
    STATE(46), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(142), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [502] = 5,
    ACTIONS(144), 1,
      anon_sym_LF,
    STATE(17), 1,
      aux_sym__whitespace,
    STATE(52), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(146), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [520] = 5,
    ACTIONS(144), 1,
      anon_sym_LF,
    STATE(27), 1,
      aux_sym__whitespace,
    STATE(52), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(148), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [538] = 6,
    ACTIONS(127), 1,
      aux_sym__quantity_number_token1,
    ACTIONS(129), 1,
      aux_sym__quantity_number_token2,
    STATE(22), 1,
      aux_sym__quantity_dot,
    STATE(30), 1,
      sym_quantity,
    STATE(35), 1,
      sym__quantity_number,
    ACTIONS(125), 2,
      anon_sym_DOT,
      anon_sym_SPACE,
  [558] = 5,
    ACTIONS(150), 1,
      anon_sym_LF,
    STATE(17), 1,
      aux_sym__whitespace,
    STATE(56), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(146), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [576] = 5,
    ACTIONS(152), 1,
      anon_sym_LF,
    STATE(17), 1,
      aux_sym__whitespace,
    STATE(59), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(146), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [594] = 7,
    ACTIONS(154), 1,
      sym_account,
    ACTIONS(156), 1,
      anon_sym_STAR,
    ACTIONS(158), 1,
      anon_sym_SPACE,
    ACTIONS(160), 1,
      anon_sym_TAB,
    STATE(32), 1,
      aux_sym_org_heading_repeat1,
    STATE(36), 1,
      aux_sym__whitespace,
    STATE(54), 1,
      sym_org_heading,
  [616] = 5,
    ACTIONS(150), 1,
      anon_sym_LF,
    STATE(28), 1,
      aux_sym__whitespace,
    STATE(56), 1,
      sym_comment,
    ACTIONS(7), 2,
      anon_sym_POUND,
      anon_sym_SEMI,
    ACTIONS(162), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [634] = 4,
    ACTIONS(164), 1,
      anon_sym_STAR,
    STATE(34), 1,
      aux_sym__whitespace,
    STATE(38), 1,
      aux_sym_org_heading_repeat1,
    ACTIONS(166), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [648] = 4,
    ACTIONS(164), 1,
      anon_sym_STAR,
    STATE(37), 1,
      aux_sym__whitespace,
    STATE(38), 1,
      aux_sym_org_heading_repeat1,
    ACTIONS(168), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [662] = 1,
    ACTIONS(170), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
  [670] = 4,
    ACTIONS(172), 1,
      sym__2d,
    ACTIONS(174), 1,
      sym__4d,
    STATE(17), 1,
      aux_sym__whitespace,
    ACTIONS(146), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [684] = 1,
    ACTIONS(133), 5,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_SEMI,
      anon_sym_SPACE,
      anon_sym_TAB,
  [692] = 5,
    ACTIONS(113), 1,
      anon_sym_STAR,
    ACTIONS(118), 1,
      sym_account,
    ACTIONS(176), 1,
      anon_sym_SPACE,
    ACTIONS(179), 1,
      anon_sym_TAB,
    STATE(36), 1,
      aux_sym__whitespace,
  [708] = 4,
    ACTIONS(158), 1,
      anon_sym_SPACE,
    ACTIONS(160), 1,
      anon_sym_TAB,
    ACTIONS(172), 1,
      sym_account,
    STATE(36), 1,
      aux_sym__whitespace,
  [721] = 3,
    ACTIONS(182), 1,
      anon_sym_STAR,
    STATE(38), 1,
      aux_sym_org_heading_repeat1,
    ACTIONS(185), 2,
      anon_sym_SPACE,
      anon_sym_TAB,
  [732] = 4,
    ACTIONS(11), 1,
      sym__2d,
    ACTIONS(13), 1,
      sym__4d,
    STATE(44), 1,
      sym__single_date,
    STATE(63), 1,
      sym_date,
  [745] = 2,
    ACTIONS(187), 1,
      anon_sym_LF,
    ACTIONS(189), 1,
      aux_sym_transaction_token1,
  [752] = 2,
    ACTIONS(191), 1,
      anon_sym_LF,
    ACTIONS(193), 1,
      aux_sym_transaction_token1,
  [759] = 2,
    ACTIONS(195), 1,
      anon_sym_LF,
    ACTIONS(197), 1,
      sym__dsep,
  [766] = 2,
    ACTIONS(199), 1,
      anon_sym_LF,
    ACTIONS(201), 1,
      aux_sym_transaction_token1,
  [773] = 1,
    ACTIONS(203), 1,
      anon_sym_LF,
  [777] = 1,
    ACTIONS(205), 1,
      sym__2d,
  [781] = 1,
    ACTIONS(144), 1,
      anon_sym_LF,
  [785] = 1,
    ACTIONS(207), 1,
      sym__2d,
  [789] = 1,
    ACTIONS(209), 1,
      anon_sym_LF,
  [793] = 1,
    ACTIONS(211), 1,
      anon_sym_LF,
  [797] = 1,
    ACTIONS(213), 1,
      anon_sym_LF,
  [801] = 1,
    ACTIONS(215), 1,
      anon_sym_LF,
  [805] = 1,
    ACTIONS(150), 1,
      anon_sym_LF,
  [809] = 1,
    ACTIONS(217), 1,
      aux_sym_comment_token1,
  [813] = 1,
    ACTIONS(219), 1,
      sym_account,
  [817] = 1,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
  [821] = 1,
    ACTIONS(152), 1,
      anon_sym_LF,
  [825] = 1,
    ACTIONS(223), 1,
      sym__2d,
  [829] = 1,
    ACTIONS(225), 1,
      sym__dsep,
  [833] = 1,
    ACTIONS(227), 1,
      anon_sym_LF,
  [837] = 1,
    ACTIONS(229), 1,
      sym__dsep,
  [841] = 1,
    ACTIONS(231), 1,
      sym_account,
  [845] = 1,
    ACTIONS(197), 1,
      sym__dsep,
  [849] = 1,
    ACTIONS(233), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 219,
  [SMALL_STATE(9)] = 258,
  [SMALL_STATE(10)] = 280,
  [SMALL_STATE(11)] = 295,
  [SMALL_STATE(12)] = 310,
  [SMALL_STATE(13)] = 325,
  [SMALL_STATE(14)] = 340,
  [SMALL_STATE(15)] = 355,
  [SMALL_STATE(16)] = 370,
  [SMALL_STATE(17)] = 385,
  [SMALL_STATE(18)] = 402,
  [SMALL_STATE(19)] = 416,
  [SMALL_STATE(20)] = 436,
  [SMALL_STATE(21)] = 456,
  [SMALL_STATE(22)] = 468,
  [SMALL_STATE(23)] = 484,
  [SMALL_STATE(24)] = 502,
  [SMALL_STATE(25)] = 520,
  [SMALL_STATE(26)] = 538,
  [SMALL_STATE(27)] = 558,
  [SMALL_STATE(28)] = 576,
  [SMALL_STATE(29)] = 594,
  [SMALL_STATE(30)] = 616,
  [SMALL_STATE(31)] = 634,
  [SMALL_STATE(32)] = 648,
  [SMALL_STATE(33)] = 662,
  [SMALL_STATE(34)] = 670,
  [SMALL_STATE(35)] = 684,
  [SMALL_STATE(36)] = 692,
  [SMALL_STATE(37)] = 708,
  [SMALL_STATE(38)] = 721,
  [SMALL_STATE(39)] = 732,
  [SMALL_STATE(40)] = 745,
  [SMALL_STATE(41)] = 752,
  [SMALL_STATE(42)] = 759,
  [SMALL_STATE(43)] = 766,
  [SMALL_STATE(44)] = 773,
  [SMALL_STATE(45)] = 777,
  [SMALL_STATE(46)] = 781,
  [SMALL_STATE(47)] = 785,
  [SMALL_STATE(48)] = 789,
  [SMALL_STATE(49)] = 793,
  [SMALL_STATE(50)] = 797,
  [SMALL_STATE(51)] = 801,
  [SMALL_STATE(52)] = 805,
  [SMALL_STATE(53)] = 809,
  [SMALL_STATE(54)] = 813,
  [SMALL_STATE(55)] = 817,
  [SMALL_STATE(56)] = 821,
  [SMALL_STATE(57)] = 825,
  [SMALL_STATE(58)] = 829,
  [SMALL_STATE(59)] = 833,
  [SMALL_STATE(60)] = 837,
  [SMALL_STATE(61)] = 841,
  [SMALL_STATE(62)] = 845,
  [SMALL_STATE(63)] = 849,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_entry, 4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_day_entry, 4), SHIFT(32),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day_entry, 4),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_day_entry_repeat1, 2),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(41),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(32),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(29),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_day_entry_repeat1, 2), SHIFT_REPEAT(29),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_day_entry_repeat1, 2),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_entry, 3),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_day_entry, 3), SHIFT(32),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day_entry, 3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day_entry, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_day_entry, 2), SHIFT(32),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_day_entry, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(58),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quantity_number, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 8),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 8),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 7),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 6),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 5),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 5),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_transaction, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transaction, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__whitespace, 2),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__whitespace, 2), SHIFT_REPEAT(17),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__whitespace, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__quantity_dot, 2),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__quantity_dot, 2), SHIFT_REPEAT(18),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantity, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_quantity, 1), SHIFT(18),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quantity_number, 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_org_heading, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_org_heading, 2),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__whitespace, 2), SHIFT_REPEAT(36),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__whitespace, 2), SHIFT_REPEAT(36),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_org_heading_repeat1, 2), SHIFT_REPEAT(38),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_org_heading_repeat1, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_date, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_date, 5),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [221] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_timedot(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
